# Generated by Django 3.2.9 on 2022-04-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('prenom', models.CharField(max_length=200, verbose_name='prenom')),
                ('age', models.IntegerField()),
                ('profile', models.URLField(verbose_name='profile')),
                ('lettre_de_motivation', models.TextField(max_length=500, verbose_name='lettre_motivation')),
                ('CV', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CV_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TextCV', models.TextField(max_length=5000, verbose_name='cvtext')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.compte')),
            ],
        ),
    ]
